name: Kickstarter の プレッジ の情報を取得する

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: ビルド ～ 実行 のテスト
    runs-on: ubuntu-latest
    steps:
    - name: $ git clone する
      uses: actions/checkout@v4
    - name: Node.js のセットアップを行う
      uses: actions/setup-node@v4
      with:
        cache: yarn
        node-version-file: .node-version
    - name: $ yarn install
      run: |
        yarn install --frozen-lockfile
    - name: ESLint
      run: |
        npx eslint --no-config-lookup --debug
    - name: ビルドする
      run: |
        yarn build
    - name: （未実装）CLI の挙動を確認する
      run: |
        echo '[実行例] ./ks_pledges.js --version'
        echo '[実行例] ./ks_pledges.js --help'
    - name: （未実装）CLI を実行する
      run: |
        echo '[実行例] ././ks_pledges.js --creator rabbitandbearstudios --project eiyuden-chronicle-hundred-heroes -o output/ks_pledges_by_github_actions.csv'
        echo '[実行例] ././ks_pledges.js --creator doublekickstarter --project armed-fantasia-and-penny-blood -o output/ks_pledges_by_github_actions.csv'
    - name: 生成された CSV ファイルなどをアーカイブする
      uses: actions/upload-artifact@v4
      with:
        name: created-csv-file
        path: |
          output
